-- 1. Drop existing tables if they exist (Clean Slate for Dev)
drop table if exists listings;
drop table if exists listing_types;
drop table if exists sub_categories;
drop table if exists categories;

-- 2. Create Tables

-- Level 1: Categories (Real Estate, Jobs)
create table categories (
  id text primary key, -- e.g. 'housing'
  label text not null,
  icon text
);

-- Level 2: SubCategories (For Rent, For Sale)
create table sub_categories (
  id bigint generated by default as identity primary key,
  category_id text references categories(id) on delete cascade not null,
  label text not null
);

-- Level 3: ListingTypes (Long Term Rentals, Houses for Sale)
create table listing_types (
  id bigint generated by default as identity primary key,
  sub_category_id bigint references sub_categories(id) on delete cascade not null,
  label text not null
);

-- Level 4: Listings (The actual Items)
create table listings (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  description text,
  price numeric,
  currency text default 'CAD',
  price_type text default 'amount', -- amount, free, contact, swap
  
  -- Category Hierarchy
  category_id text references categories(id),
  sub_category_label text, -- Store label for simplicity in some views
  sub_item_label text,
  
  -- Form Metadata
  ad_type text default 'offering', -- offering, wanted
  for_sale_by text default 'owner', -- owner, business
  item_condition text, -- new, used, etc
  
  -- Contact Info
  contact_name text,
  contact_phone text,
  contact_email text,
  hide_phone_on_ad boolean default false,
  
  -- Location
  city text,
  postal_code text,
  latitude numeric,
  longitude numeric,
  
  -- Ownership
  user_id uuid references auth.users(id),
  
  -- Content & Media
  images text[],
  tags text[],
  youtube_video_url text,
  website_url text,
  
  -- Dynamic attributes (bedrooms, kilometers, salary range)
  attributes jsonb default '{}'::jsonb,
  
  -- System Fields
  boost_plan text,
  status text default 'active', -- active, sold, expired
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3. Enable RLS
alter table categories enable row level security;
alter table sub_categories enable row level security;
alter table listing_types enable row level security;
alter table listings enable row level security;

-- 4. Create Policies

-- READ: Public
create policy "Public view categories" on categories for select using (true);
create policy "Public view sub_categories" on sub_categories for select using (true);
create policy "Public view listing_types" on listing_types for select using (true);
-- RLS Policies for Listings
ALTER TABLE listings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for listings" ON listings
    FOR SELECT USING (status = 'active');

-- WRITE: Seed/Migration Policies (TEMPORARY - Disable after migration)
create policy "Allow insert categories" on categories for insert with check (true);
create policy "Allow insert sub_categories" on sub_categories for insert with check (true);
create policy "Allow insert listing_types" on listing_types for insert with check (true);
-- create policy "Allow insert listings" on listings for insert with check (true); -- Replaced by authenticated user policy

-- WRITE: Authenticated User Policies (For Listings)
CREATE POLICY "Allow authenticated users to create listings" ON listings
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to update their own listings" ON listings
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Allow users to delete their own listings" ON listings
    FOR DELETE USING (auth.uid() = user_id);

-- 5. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  full_name text,
  phone text,
  email text,
  avatar_url text,
  auth_provider text,
  last_login_at timestamptz,
  block_features jsonb default '{}'::jsonb,
  updated_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now()
);

-- Enable RLS for Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Email Logs table for debugging triggers
CREATE TABLE IF NOT EXISTS public.email_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_type TEXT NOT NULL,
    recipient TEXT,
    payload JSONB,
    request_url TEXT,
    response_status INTEGER,
    response_body TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.email_logs ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
CREATE POLICY "Users can update own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- 6. Trigger for automatic profile creation
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, phone, email, avatar_url, auth_provider, last_login_at)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', ''),
    new.phone,
    new.email,
    COALESCE(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', ''),
    COALESCE(new.raw_app_meta_data->>'provider', 'email'),
    new.created_at
  )
  ON CONFLICT (id) DO UPDATE
  SET 
    email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    phone = EXCLUDED.phone,
    avatar_url = EXCLUDED.avatar_url,
    auth_provider = EXCLUDED.auth_provider,
    last_login_at = EXCLUDED.last_login_at;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger execution for insert
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Trigger function for update
CREATE OR REPLACE FUNCTION public.handle_update_user()
RETURNS trigger AS $$
BEGIN
  UPDATE public.profiles
  SET 
    full_name = new.raw_user_meta_data->>'full_name',
    phone = new.phone,
    email = new.email,
    updated_at = now()
  WHERE id = new.id;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger execution for update
DROP TRIGGER IF EXISTS on_auth_user_updated ON auth.users;
CREATE TRIGGER on_auth_user_updated
  AFTER UPDATE ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_update_user();

-- Trigger function for login tracking
CREATE OR REPLACE FUNCTION public.handle_user_login()
RETURNS trigger AS $$
BEGIN
  -- Only update profiles if last_sign_in_at actually changed (meaning a new login)
  IF OLD.last_sign_in_at IS DISTINCT FROM NEW.last_sign_in_at THEN
    UPDATE public.profiles
    SET last_login_at = NEW.last_sign_in_at
    WHERE id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger execution for login tracking
DROP TRIGGER IF EXISTS on_auth_user_login ON auth.users;
CREATE TRIGGER on_auth_user_login
  AFTER UPDATE OF last_sign_in_at ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_user_login();


-- 7. Chat System
create table if not exists public.chat_rooms (
  id uuid default gen_random_uuid() primary key,
  listing_id uuid references listings(id) on delete set null,
  buyer_id uuid references auth.users(id) not null,
  seller_id uuid references auth.users(id) not null,
  last_message text,
  last_message_at timestamptz default now(),
  created_at timestamptz default now(),
  unique(listing_id, buyer_id, seller_id)
);

create table if not exists public.chat_messages (
  id uuid default gen_random_uuid() primary key,
  room_id uuid references chat_rooms(id) on delete cascade not null,
  sender_id uuid references auth.users(id) not null,
  content text not null,
  message_type text default 'text',
  file_url text,
  file_name text,
  file_size bigint,
  is_read boolean default false,
  created_at timestamptz default now()
);

-- RLS for Chat System
alter table chat_rooms enable row level security;
alter table chat_messages enable row level security;

-- Chat Rooms: Only participants can view their rooms
create policy "Users can view their own chat rooms" on chat_rooms
  for select using (auth.uid() = buyer_id or auth.uid() = seller_id);

create policy "Users can create chat rooms" on chat_rooms
  for insert with check (auth.uid() = buyer_id);

-- Chat Messages: Only participants of the room can view/insert messages
create policy "Users can view messages in their rooms" on chat_messages
  for select using (
    exists (
      select 1 from chat_rooms
      where id = chat_messages.room_id
      and (buyer_id = auth.uid() or seller_id = auth.uid())
    )
  );

create policy "Users can send messages in their rooms" on chat_messages
  for insert with check (
    auth.uid() = sender_id and
    exists (
      select 1 from chat_rooms
      where id = chat_messages.room_id
      and (buyer_id = auth.uid() or seller_id = auth.uid())
    )
  );

-- Enable Realtime
alter publication supabase_realtime add table chat_rooms;
alter publication supabase_realtime add table chat_messages;

-- 8. Seed Data for Events Category
INSERT INTO categories (id, label, icon) VALUES ('events', 'Events', '🎉') ON CONFLICT (id) DO NOTHING;

INSERT INTO sub_categories (category_id, label) VALUES
  ('events', 'Cultural events'),
  ('events', 'Music or dance programs'),
  ('events', 'Festivals (Ugadi, Diwali, Sankranti, etc.)'),
  ('events', 'Business seminars'),
  ('events', 'Educational workshops'),
  ('events', 'Kids and family events'),
  ('events', 'Sports tournaments')
-- ... (existing sub-categories)
ON CONFLICT DO NOTHING;

-- 9. Email Trigger Functions (Updated for fixes and logging)

CREATE OR REPLACE FUNCTION public.get_email_function_headers(request_headers JSONB)
RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
  auth_val TEXT;
  apikey_val TEXT;
BEGIN
  auth_val := COALESCE(
    request_headers->>'authorization',
    CASE 
      WHEN request_headers->>'anon' IS NOT NULL AND request_headers->>'anon' != '' 
      THEN 'Bearer ' || (request_headers->>'anon') 
      ELSE 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxdWhyZXdwdXh6amxleGdoc2lvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTk3NzkyNSwiZXhwIjoyMDg1NTUzOTI1fQ.SRUl6Mkr_C7i_9aohf5W7cT-kMVYUGb_6J4BTC8NKug'
    END
  );
  apikey_val := COALESCE(request_headers->>'apikey', request_headers->>'anon', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxdWhyZXdwdXh6amxleGdoc2lvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTk3NzkyNSwiZXhwIjoyMDg1NTUzOTI1fQ.SRUl6Mkr_C7i_9aohf5W7cT-kMVYUGb_6J4BTC8NKug');
  RETURN jsonb_strip_nulls(jsonb_build_object(
    'Content-Type', 'application/json',
    'x-internal-key', 'canada-telugu-internal-key-2026',
    'apikey', apikey_val,
    'Authorization', auth_val
  ));
END;
$$;

CREATE OR REPLACE FUNCTION public.trigger_welcome_email()
RETURNS trigger AS $$
DECLARE
  base_url text := 'https://gquhrewpuxzjlexghsio.supabase.co';
  request_headers jsonb;
  log_id uuid;
  req_body jsonb;
BEGIN
  BEGIN request_headers := current_setting('request.headers', true)::jsonb; EXCEPTION WHEN OTHERS THEN request_headers := '{}'::jsonb; END;

  IF TG_OP = 'UPDATE' THEN
    IF NOT (COALESCE(OLD.is_verified, false) IS FALSE AND NEW.is_verified IS TRUE) THEN RETURN NEW; END IF;
  ELSIF TG_OP = 'INSERT' THEN
    IF NOT (NEW.is_verified IS TRUE) THEN RETURN NEW; END IF;
  END IF;

  req_body := jsonb_build_object('event', 'welcome', 'payload', jsonb_build_object('to', NEW.email, 'name', NEW.full_name));
  INSERT INTO public.email_logs (event_type, recipient, payload, request_url) VALUES ('welcome', NEW.email, req_body, base_url || '/functions/v1/send-email') RETURNING id INTO log_id;

  BEGIN
    PERFORM net.http_post(url := base_url || '/functions/v1/send-email', headers := public.get_email_function_headers(request_headers), body := req_body);
    UPDATE public.email_logs SET response_status = 202 WHERE id = log_id;
  EXCEPTION WHEN OTHERS THEN
    UPDATE public.email_logs SET error_message = SQLERRM WHERE id = log_id;
  END;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- 1. AD STATUS Emails: Strictly handle using profiles.email
CREATE OR REPLACE FUNCTION public.trigger_ad_status_change_email()
RETURNS trigger AS $$
DECLARE
  base_url text;
  profile_record record;
  request_headers jsonb;
  send_email boolean := false;
BEGIN
  -- Determine if we should send the email
  IF TG_OP = 'INSERT' THEN
    IF NEW.status = 'active' THEN send_email := true; END IF;
  ELSIF TG_OP = 'UPDATE' THEN
    IF OLD.status IS DISTINCT FROM NEW.status AND (NEW.status = 'active' OR NEW.status = 'blocked') THEN
      send_email := true;
    END IF;
  END IF;

  IF send_email THEN
    -- Strictly get email from profiles table linked to the listing owner
    SELECT * INTO profile_record FROM public.profiles WHERE id = NEW.user_id;
    
    IF FOUND AND profile_record.email IS NOT NULL THEN
      BEGIN
        request_headers := current_setting('request.headers', true)::json;
      EXCEPTION WHEN OTHERS THEN
        request_headers := '{}'::jsonb;
      END;

      base_url := COALESCE(request_headers->>'host', 'gquhrewpuxzjlexghsio.supabase.co');
      IF NOT (base_url LIKE 'http%') THEN base_url := 'https://' || base_url; END IF;

      PERFORM net.http_post(
        url := base_url || '/functions/v1/send-email',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'x-internal-key', 'canada-telugu-internal-key-2026',
          'Authorization', 'Bearer ' || COALESCE(request_headers->>'authorization', request_headers->>'anon', '')
        ),
        body := jsonb_build_object(
          'event', 'ad_status_change',
          'payload', jsonb_build_object(
            'to', profile_record.email,
            'subject', CASE WHEN NEW.status = 'active' THEN 'Your Ad is Live: ' || NEW.title ELSE 'Ad Update: ' || NEW.title END,
            'new_status', NEW.status,
            'title', NEW.title,
            'id', NEW.id,
            'reason', CASE WHEN NEW.status = 'blocked' THEN 'Violation of posting guidelines' ELSE NULL END
          )
        )
      );
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2. NEW INQUIRY Emails: Strictly handle using profiles.email of the recipient
CREATE OR REPLACE FUNCTION public.trigger_new_inquiry_email()
RETURNS trigger AS $$
DECLARE
  room_record RECORD;
  listing_record RECORD;
  recipient_email TEXT;
  sender_name TEXT;
  payload JSONB;
  request_headers JSONB;
  base_url TEXT;
BEGIN
  -- Get room and listing details
  SELECT * INTO room_record FROM public.chat_rooms WHERE id = NEW.room_id;
  IF NOT FOUND THEN RETURN NEW; END IF;

  SELECT * INTO listing_record FROM public.listings WHERE id = room_record.listing_id;
  IF NOT FOUND THEN RETURN NEW; END IF;

  -- Only send email for the first message (Inquiry)
  IF (SELECT count(*) FROM public.chat_messages WHERE room_id = NEW.room_id) != 1 THEN
    RETURN NEW;
  END IF;

  -- Strictly determine recipient email from the profiles table
  IF NEW.sender_id = room_record.buyer_id THEN
    SELECT email INTO recipient_email FROM public.profiles WHERE id = room_record.seller_id;
  ELSE
    SELECT email INTO recipient_email FROM public.profiles WHERE id = room_record.buyer_id;
  END IF;

  SELECT full_name INTO sender_name FROM public.profiles WHERE id = NEW.sender_id;

  IF recipient_email IS NOT NULL THEN
    BEGIN
      request_headers := current_setting('request.headers', true)::json;
    EXCEPTION WHEN OTHERS THEN
      request_headers := '{}'::json;
    END;

    base_url := COALESCE(request_headers->>'host', 'gquhrewpuxzjlexghsio.supabase.co');
    IF NOT (base_url LIKE 'http%') THEN base_url := 'https://' || base_url; END IF;

    PERFORM net.http_post(
      url := base_url || '/functions/v1/send-email',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-internal-key', 'canada-telugu-internal-key-2026',
        'Authorization', 'Bearer ' || COALESCE(request_headers->>'authorization', request_headers->>'anon', '')
      ),
      body := jsonb_build_object(
        'event', 'new_inquiry',
        'payload', jsonb_build_object(
          'to', recipient_email,
          'subject', 'New Inquiry for: ' || listing_record.title,
          'listing_title', listing_record.title,
          'sender_name', COALESCE(sender_name, 'Interested Buyer'),
          'message', NEW.content
        )
      )::text
    );
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Ensure triggers are correctly assigned and pointing to these functions
DROP TRIGGER IF EXISTS on_ad_status_updated_email ON public.listings;
CREATE TRIGGER on_ad_status_updated_email
  AFTER INSERT OR UPDATE OF status ON public.listings
  FOR EACH ROW EXECUTE PROCEDURE public.trigger_ad_status_change_email();

DROP TRIGGER IF EXISTS on_new_message_email ON public.chat_messages;
CREATE TRIGGER on_new_message_email
  AFTER INSERT ON public.chat_messages
  FOR EACH ROW EXECUTE PROCEDURE public.trigger_new_inquiry_email();

-- 4. Clean up any misplaced triggers that might have been accidentally created in the past
DROP TRIGGER IF EXISTS on_ad_status_updated_email ON public.chat_messages;
DROP TRIGGER IF EXISTS on_ad_status_updated_email ON public.chat_rooms;
